import * as fs from 'fs';
import * as path from 'path';

// This file is automatically generated by the `tools/reindex.ts` script.
const note = 'This file is automatically generated by the `tools/reindex.ts` script.';

interface IndexEntry {
  path: string;
  type: 'file' | 'directory';
  children?: IndexEntry[];
  isEmpty?: boolean;
  size?: number;
}

/**
 * Recursively scans a directory and builds an index structure
 */
function scanDirectory(dirPath: string, relativePath: string = ''): IndexEntry | null {
  const fullPath = path.join(dirPath, relativePath);
  
  // Skip the index.json file
  if (relativePath === 'index.json') {
    return null;
  }
  
  const stats = fs.statSync(fullPath);
  
  if (stats.isFile()) {
    // For files, return basic info
    const content = fs.readFileSync(fullPath, 'utf8');
    return {
      path: relativePath,
      type: 'file',
      isEmpty: content.trim().length === 0,
      size: stats.size
    };
  } else if (stats.isDirectory()) {
    // For directories, scan all children
    const items = fs.readdirSync(fullPath);
    const children = items.map(item => 
      scanDirectory(dirPath, path.join(relativePath, item))
    ).filter(entry => entry !== null); // Filter out null entries (skipped files)
    
    return {
      path: relativePath || '/',
      type: 'directory',
      children
    };
  }
  
  throw new Error(`Unknown file type: ${fullPath}`);
}

/**
 * Main function to generate the index
 */
function generateIndex() {
  console.log('Generating index.json...');
  
  const indexDir = './index';
  
  // Ensure the index directory exists
  if (!fs.existsSync(indexDir)) {
    console.error(`Error: Directory ${indexDir} does not exist`);
    process.exit(1);
  }
  
  // Generate the index structure
  const indexStructure = scanDirectory(indexDir);
  
  // Add metadata
  const indexJson = {
    "!!NOTE!!": note,
    index: indexStructure
  };
  
  // Write the index file
  const outputPath = path.join(indexDir, 'index.json');
  fs.writeFileSync(
    outputPath, 
    JSON.stringify(indexJson, null, 2),
    'utf8'
  );
  
  console.log(`Index successfully generated at ${outputPath}`);
}

generateIndex();

