name: Validate JSONs

on: [push, pull_request]

jobs:
  verify-json:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v1
    - name: Validate JSONs
      run: bash ./tools/scripts/jsonlint.sh
      # env:
        
